### ISSUE TITLE
New Error on redeploy

### ISSUE THREAD

**Issue by pachax001** [weebzone/WZML#103]
File "/usr/src/app/bot/__init__.py", line 921, in <module>
mirrorbot-app-1  |     tgDefaults = Defaults(parse_mode='HTML', disable_web_page_preview=True, allow_sending_without_reply=True, run_async=True)
mirrorbot-app-1  | TypeError: __init__() got an unexpected keyword argument 'run_async'

**Comment by pachax001** [comment]
Problem is with when UPDATE_PACKAGES = "True"
This updates the python-telegram-bot to latest version

**Comment by weebzone** [comment]
fixed
