### ISSUE TITLE
Deploying Error

### ISSUE THREAD

**Issue by SoloLeveling7seven** [weebzone/WZML#109]
**Describe the bug**

**To Reproduce**
sudo docker build . -t mirror-bot

**Expected behavior**

**Screenshots**
![photo_6183975448896189644_y](https://user-images.githubusercontent.com/109235836/211154278-25f8ca96-062d-4d29-86cb-9b043827e1ca.jpg)

**Additional context**

**Comment by MinorX** [comment]
Google "Temporary failure in name resolution error 3"
