### ISSUE TITLE
Mega Module Not found 

### ISSUE THREAD

**Issue by sabitahmad** [weebzone/WZML#120]
When I am trying to deploy in heroku (master branch) its throwing error module named mega not found

![IMG_20230118_140446_229](https://user-images.githubusercontent.com/117693743/213116838-10617c52-ca7b-4bdf-b850-7f7dafd1a113.jpg)

Look into this..

**Comment by weebzone** [comment]
use the heroku branch for heroku
master branch is not compatible in heroku
