### ISSUE TITLE
Auto delete command message !

### ISSUE THREAD

**Issue by anymeofu** [weebzone/WZML#123]
**Describe the bug**
When ever we clone/mirror the links or telegram files gets deleted by bot automatically despite keeping auto upload message duration to -1.

**To Reproduce**
1. mirror/clone/ TG files
2. After the task is complete bot deletes the source link/command/TG file

**Expected behavior**
We expect bot not to delete the command/link/files

**Screenshots**
<img width="277" alt="image" src="https://user-images.githubusercontent.com/76214556/213858820-2857fdf7-d728-4283-aa8d-543f1bfbaa1f.png">

**Additional context**
Tried turning off Link logs, view links, show links - doesn't help
Note: Force bot PM is not used either

**Comment by weebzone** [comment]
@anymeofu okk it will be fixed in next update..
