### ISSUE TITLE
Uploading Issue

### ISSUE THREAD

**Issue by manishj1200** [weebzone/WZML#125]
Upload stuck at 14MB
![Screenshot_20230126_193504_Telegram X](https://user-images.githubusercontent.com/123647316/214856808-16f0012d-dd78-4d30-9cd4-5ed96b4fbe51.jpg)

**Comment by weebzone** [comment]
@manishj1200 file issue may be

**Comment by mjwebhacks** [comment]
may be pyrogram is not stable these days you can close the issue thanks for reply

**Comment by manishj1200** [comment]
maybe pyrogram is not stable these days you can close the issue thanks for reply

**Comment by manishj1200** [comment]
closing issue
