### ISSUE TITLE
update prename function 

### ISSUE THREAD

**Issue by NesamaniX1** [weebzone/WZML#19]
Prename Function is very useful . I want some improvement in prename module . 

1. When mirror  filename change to prename .
Example:- 
 Before Mirror
  ` www.TamilBlasters.skin - Kana Kaanum Kaalangal (2022) S02 EP(83-86) [HQHDRip - x264 - AAC - 500MB].mkv`
  After Mirror 
  `@Prename - Kana Kaanum Kaalangal (2022) S02 EP(83-86) [HQHDRip - x264 - AAC - 500MB].mkv`

2. If link have already any prenames like `@prename - Kana Kaanum Kaalangal (2022) S02 EP(83-86) [HQHDRip - x264 - AAC - 500MB].mkv`
Automatically change to user's prename
Example : 
 `@newprename - Kana Kaanum Kaalangal (2022) S02 EP(83-86) [HQHDRip - x264 - AAC - 500MB].mkv`

Thank you

**Comment by weebzone** [comment]
working on this soon u will get the update
