### ISSUE TITLE
Prename doubt

### ISSUE THREAD

**Issue by JAsuran** [weebzone/WZML#20]
I have set prename after use qbleech file hanged in uploading with 0%

how 2 solve this

**Comment by rubandurai27** [comment]
> I have set prename after use qbleech file hanged in uploading with 0%
> 
> how 2 solve this

That's not a problem bro

**Comment by JAsuran** [comment]
> > I have set prename after use qbleech file hanged in uploading with 0%
> > how 2 solve this
> 
> That's not a problem bro

If u know solution share bro..
