### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by massmia** [weebzone/WZML#21]
I used Deploy With Github Workflow,, deploy green tick shown, but bot not working or running

![Screenshot (58)](https://user-images.githubusercontent.com/113176669/199988823-2e00d8a1-61c0-417f-a01c-d6f415afd591.png)

**Comment by carolynsteeves1** [comment]
Is github deployment banned? like deploying bot on github actions

**Comment by weebzone** [comment]
yes

**Comment by massmia** [comment]
um, I am new in programming,
Is there any tutorial ?

I stuck at heroku login (using git) ..
