### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alonelove7** [weebzone/WZML#22]
Hello dear
on vps :

root@s11612706:~/WZML-dev# sudo docker-compose up
Recreating wzml-dev_app_1 ... done
Attaching to wzml-dev_app_1
app_1  | warning: no common commits
app_1  | 2022-11-06 10:18:37,473 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
app_1  | [2022-11-06 10:18:38 +0000] [33] [INFO] Starting gunicorn 20.1.0
app_1  | [2022-11-06 10:18:38 +0000] [33] [INFO] Listening at: http://0.0.0.0:5555 (33)
app_1  | [2022-11-06 10:18:38 +0000] [33] [INFO] Using worker: sync
app_1  | [2022-11-06 10:18:38 +0000] [61] [INFO] Booting worker with pid: 61
app_1  | 2022-11-06 10:18:38,878 - root - ERROR - One or more env variables missing! Exiting now
root@s11612706:~/WZML-dev#

----------
[config.zip](https://github.com/weebzone/WZML/files/9945584/config.zip)

**Comment by weebzone** [comment]
@alonelove7 there is double (=) in owner id, telegram api in config.env 
also check rest of config by yourself

**Comment by alonelove7** [comment]
Thank you 
solved <3
