### ISSUE TITLE
Error Deploy Vps

### ISSUE THREAD

**Issue by rinrinx2** [weebzone/WZML#40]
app_1  | 2022-11-27 15:54:22,959 - bot - INFO - Creating Telegraph Account
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
app_1  |     return _run_code(code, main_globals, None,
app_1  |   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
app_1  |     exec(code, run_globals)
app_1  |   File "/usr/src/app/bot/__main__.py", line 25, in <module>
app_1  |     from .modules import authorize, list, cancel_mirror, mirror_status, mirror_leech, clone, ytdlp, shell, eval, bot_settings, \
app_1  |   File "/usr/src/app/bot/modules/imdb.py", line 15, in <module>
app_1  |     imdb = IMDb()
app_1  |   File "/usr/local/lib/python3.8/dist-packages/imdb/__init__.py", line 195, in IMDb
app_1  |     from .parser.http import IMDbHTTPAccessSystem
app_1  |   File "/usr/local/lib/python3.8/dist-packages/imdb/parser/http/__init__.py", line 165
app_1  |     'Mozilla/5.0 (X11; CrOS armv6l 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56')')
app_1  |                                                                                                                                          ^
app_1  | SyntaxError: EOL while scanning string literal

**Comment by anymeofu** [comment]
same error with me. I guess wait for fix

**Comment by rinrinx2** [comment]
Thanks
