### ISSUE TITLE
Github workflow problem

### ISSUE THREAD

**Issue by mukto781** [weebzone/WZML#6]
![Screenshot_20220928-214034_Samsung Internet](https://user-images.githubusercontent.com/63152325/192863406-74a7e639-3197-431e-ae06-01885e66dcd0.jpg)

Why this problem appears?? When I run it on github action with workflow. Your previous one was gd... Bt new update not working plz give solution.

**Comment by weebzone** [comment]
add megasdkrestclient in requirement.txt

**Comment by mukto781** [comment]
![Screenshot_20220928-221402_Samsung Internet](https://user-images.githubusercontent.com/63152325/192869221-b596ead7-18cb-4fe3-ba3e-7e2369725d9e.jpg)

After adding megasdkrestclient in requirement.txt plz give me solution
