### ISSUE TITLE
how to deploy on windows vps?

### ISSUE THREAD

**Issue by kfhm02** [weebzone/WZML#66]
i am using windows vps, but in the readme only instructions to install on linux vps, i can't deploy on windows vps. How to deploy bot on windows vps. Can you guide me in this case?

**Comment by haruo75** [comment]
windows vps?you mean RDP

**Comment by kfhm02** [comment]
yes, Cloud VPS with Windows server.

**Comment by MinorX** [comment]
Ig you can use docker on windows.

**Comment by haruo75** [comment]
it will be easy if you have administrator access to install docker and or active windows feature wsl

**Comment by weebzone** [comment]
use the telegram group for help https://t.me/WeebZ
