### ISSUE TITLE
BOT does not upload files to Drive

### ISSUE THREAD

**Issue by goldenevil47** [weebzone/WZML#68]
I have been using November update of BOT with heroku for a couple of days as december update doesnt not work for me for some reason I cant understand. But for last 2-3 days Nov update bot isnt working properly and throws an error while uploading any file to drive.

EOF occurred in violation of protocol (_ssl.c:2396)

**Comment by sherlockia2** [comment]
Yes, same issue here also.

**Comment by weebzone** [comment]
repo is fine this is an external issue
