### ISSUE TITLE
upload

### ISSUE THREAD

**Issue by alonelove7** [weebzone/WZML#83]
Hi dear
i invite you to see video please\

there is a little bug for some files on telegram upload status gets stuck

**Comment by weebzone** [comment]
check the admin permission of bot may be u did give permission to delete the mesaage

**Comment by alonelove7** [comment]
I wish that was the reason
![Capture](https://user-images.githubusercontent.com/34532101/209622310-426d9178-12ec-41f5-81eb-c432a6f2e0bf.JPG)
