### ISSUE TITLE
Is unified generator really working? 

### ISSUE THREAD

**Issue by jbook1** [weebzone/WZML#84]
I want to ask anyone who can reply that UNIFIED GENERATOR is working or not, I tried appdrive but it doesn't work gives error as invalid token.

Can anyone confirm.

**Comment by haruo75** [comment]
same as me only gdtot working

**Comment by MajnuRangeela** [comment]
> I want to ask anyone who can reply that UNIFIED GENERATOR is working or not, I tried appdrive but it doesn't work gives error as invalid token.
> 
> Can anyone confirm.

NO, script is dead because all UNIFIED GENERATORS added captcha verification except GDFlix for now.
