### ISSUE TITLE
It's  Possible Add Mirror to Gofile

### ISSUE THREAD

**Issue by ED8ET** [weebzone/WZML#88]
Hello sir

https://github.com/8figalltimepro/MOD-OF-MIRROR-BOT-BY-8  

Someone already made it  but repo is dead not working anymore.

Why request?
Td are not allowing now mirror things now...

**Comment by haruo75** [comment]
Possible

**Comment by weebzone** [comment]
yess but this repo code is outdated we are working on new code from scratch already may be on next update it will come🤞
