### ISSUE TITLE
there is a missing 

### ISSUE THREAD

**Issue by TTDIDTG** [weebzone/WZML#9]
![‏‏צילום מסך (116)](https://user-images.githubusercontent.com/98256431/193260234-5f8a907d-4cef-4a5f-84d7-0e34524f63b4.png)
![‏‏צילום מסך (115)](https://user-images.githubusercontent.com/98256431/193260239-c44e7655-a2db-4556-8f79-ecbb3a6cf520.png)
i got this error what is it?
thanks!

**Comment by bbengali** [comment]
Same error
