### ISSUE TITLE
Leech index error

### ISSUE THREAD

**Issue by Spidey2077** [weebzone/WZML#97]
**Describe the bug**
After leech is completed bot failed to send leech index message.

**Log**
bot - INFO - Leech Name: 05 Assassin’s Creed III Remastered [Day 1 Patch + All DLCs + AC Liberation + MULTi13] 2012 - [DODI Repack].zip
bot.helper.mirror_utils.upload_utils.pyrogramEngine - INFO - Leech Completed: 05 Assassin’s Creed III Remastered [Day 1 Patch + All DLCs + AC Liberation + MULTi13] 2012 - [DODI Repack].zip
bot - ERROR - Message caption is too long
bot - INFO - Cleaning Download: /usr/src/app/downloads/2633

**Comment by MajnuRangeela** [comment]
Use latest commit
